name: k3s Testing
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: debianmaster/actions-k3s@v1.0.5
      id: k3s
      with:
        version: 'v1.21.2-k3s1'
    - run: |
        kubectl get nodes
        docker exec k3s-v1.21.2-k3s1 ctr images ls
